name: Test

permissions:
  id-token: write
  contents: read
  checks: write
  pull-requests: write


on:
  push:
    branches:
      - 'main'
      - 'release/**'
      - 'buh_fixes'
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - labeled
      - ready_for_review

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}

jobs:
  test:
    name: Test
    uses: activeloopai/shared-github-actions/.github/workflows/full_test.yml@buh_fixes
    if: github.repository == 'activeloopai/deeplake'
    with:
      repo: ${{ github.repository }}
      ref: ${{ github.sha }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
      aws_role_arn: ${{ secrets.AWS_ROLE_ARN }}
      gcp_sa_credentials_json: ${{ secrets.GCP_SA_CREDENTIALS_JSON }}
      azure_creds_json: ${{ secrets.AZURE_CREDS_JSON }}
      hub_username: ${{ secrets.ACTIVELOOP_HUB_USERNAME }}
      hub_token: ${{ secrets.ACTIVELOOP_HUB_TOKEN }}
      kaggle_username: ${{ secrets.KAGGLE_USERNAME }}
      kaggle_key: ${{ secrets.KAGGLE_KEY }}
      oauth_client_id: ${{ secrets.GDRIVE_CLIENT_ID }}
      oauth_client_secret: ${{ secrets.GDRIVE_CLIENT_SECRET }}
      oauth_refresh_token: ${{ secrets.GDRIVE_REFRESH_TOKEN }}
      sonar_token: ${{ secrets.SONAR_TOKEN }}
